### ISSUE TITLE
conflict with `ecthelionvi/NeoColumn.nvim`

### ISSUE THREAD

**Issue by cxwx** [sontungexpt/stcursorword#4]
I install this plugin with `ecthelionvi/NeoColumn.nvim` same time.
bugs when enabled with `ToggleNeoColumn`

Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: Vim:E803: ID not found: 1000
stack traceback:
        [C]: in function 'matchdelete'
        ...l/share/nvim/lazy/stcursorword/lua/stcursorword/init.lua:53: in functi
on 'matchdelete'
        ...l/share/nvim/lazy/stcursorword/lua/stcursorword/init.lua:77: in functi
on 'highlight_same'
        ...l/share/nvim/lazy/stcursorword/lua/stcursorword/init.lua:158: in funct
ion <...l/share/nvim/lazy/stcursorword/lua/stcursorword/init.lua:154>

**Comment by sontungexpt** [comment]
I read the source code of this plugin and noticed that it uses fn.clearmatches, which clears all existing matches, including the match for cursorword. I can fix this by using pcall, but after toggling, the cursorword is trigger at the next movement to new word, I can't do any thing for this.

**Comment by cxwx** [comment]
暂时也只能这样了
